### ISSUE TITLE
关于在移动端使用h5的video标签的全攻略

### ISSUE THREAD

**Issue by KangXueLiang** [KangXueLiang/my-blog#1]
最近完成了一个移动端活动页面里插入视频播放的需求，现在来说一下自己的经验与碰到的坑。
既然是插入视频，用的肯定是h5的video标签了，没啥异议，直接开干！对了，先来看一下效果图：

[六小龄童领全民拜年](http://m.ds.cn/special_event/new_year_friend_circle.html)   👈点击这里

先来简单分析一下video标签。
## 通用属性
[MDN](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video)上的属性有以下几个：（只说主要的、常用的）
* autoplay 自动播放属性。实践起来没什么卵用。
* controls 加上控制条，允许用户控制视频的播放，包括音量，跨帧，暂停/恢复播放。当然，也没什么卵用。
* loop 是否自动循环播放。
* preload 告诉浏览器作者认为达到最佳的用户体验的方式是什么。
	* none 浏览器不缓存视频
	* metadata 不缓存视频，但会取得视频的一些数据，如视频长度
	* auto 优先下载视频，不管用户看不看
	* 空字符串 指auto
	ps:这里需要注意一点，如果设置了autoplay，但是preload的值为none,也会自动缓存视频，因为autoplay的优先级高于proload
* poster 海报，就是视频还没开始播放的时候的标签所展示的图片。
* src 资源路径
* height/weight 高、宽

### iOS
* webkit-playsinline和playsinline：视频播放时局域播放，不脱离文档流 。但是这个属性比较特别， 需要嵌入网页的APP比如WeChat中UIwebview 的allowsInlineMediaPlayback = YES webview.allowsInlineMediaPlayback = YES，才能生效。换句话说，如果APP不设置，你页面中加了这标签也无效，这也就是为什么安卓手机WeChat 播放视频总是全屏，因为APP不支持playsinline，而ISO的WeChat却支持。
这里就要补充下，如果是想做全屏直播或者全屏H5体验的用户，IOS需要设置删除 webkit-playsinline 标签，因为你设置 false 是不支持的 ，安卓则不需要，因为默认全屏。但这时候全屏是有播放控件的，无论你有没有设置control。 做直播的可能用得着播放控件，但是全屏H5是不需要的，那么去除全屏播放时候的控件，需要以下设置：同层播放
* x-webkit-airplay="allow"：这个属性应该是使此视频支持ios的AirPlay功能。使用AirPlay可以直接从使用iOS的设备上的不同位置播放视频、音乐还有照片文件，也就是说通过AirPlay功能可以实现影音文件的无线播放，当然前提是播放的终端设备也要支持相应的功能

### android
* x5-video-player-type: 启用同层H5播放器，就是在视频全屏的时候，div可以呈现在视频层上，也是WeChat安卓版特有的属性。同层播放别名也叫做沉浸式播放，播放的时候看似全屏，但是已经除去了control和微信的导航栏，只留下"X"和"<"两键。目前的同层播放器只在Android（包括微信）上生效，暂时不支持iOS。至于为什么同层播放只对安卓开放，是因为安卓不能像ISO一样局域播放，默认的全屏会使得一些界面操作被阻拦，如果是全屏H5还好，但是做直播的话，诸如弹幕那样的功能就无法实现了，所以这时候同层播放的概念就解决了这个问题。不过在测试的过程中发现，不同版本的IOS和安卓效果略有不同
* x5-video-orientation: 声明播放器支持的方向，可选值landscape 横屏, portraint竖屏。默认值portraint。无论是直播还是全屏H5一般都是竖屏播放，但是这个属性需要x5-video-player-type开启H5模式
* x5­-video­-player­-fullscreen:全屏设置。它又两个属性值，ture和false，true支持全屏播放，false不支持全屏播放。其实，IOS 微信浏览器是Chrome的内核，相关的属性都支持，也是为什么X5同层播放不支持的原因。安卓微信浏览器是X5内核，一些属性标签比如playsinline就不支持，所以始终全屏。

## 方法
再来说两个方法：
* ended 结束播放的回调
* timeupdate 检测播放时间的回调

## 实践
所以一般来说，一个video标签长这样：(vue框架)
```js
          <video id="video" 
                 src="/video1.mp4"                   // 资源路径
				 controls = "true"                      // 是否有控制条
                 poster="/begin.jpg9"               // 视频封面
                 preload="auto"                        // 加载的形式
                 x-webkit-airplay="allow"          // 使此视频支持ios的AirPlay功能
                 webkit-playsinline="true"         // 视频播放时局域播放，不脱离文档流.需要APP支持，目前ios支持
                 playsinline="true"
				 x5-video-player-type="h5"        // 启用H5播放器,是wechat安卓版特性
				 x5-video-player-fullscreen="true"   // 安卓机全屏设置
                 @timeupdate="update()"         // 检测播放时间回调
                 @ended="playEnd()">              // 播放结束回调
            您的设备或浏览器暂不支持 video 标签。
          </video>
```

## 全屏播放及隐藏控制条
对于iOS来说
```js
<video id="video" src="xx.mp4" playsinline webkit-playsinline></video>
```
即可。

对于安卓来说，有两种办法
第一种
```js
<div>
	<video id="video" 
		src="video.mp4"  
		x5-video-player-type="h5"
		x5-video-player-fullscreen="true"
		x5-video-orientation="portraint"
		style="object-fit:fill">
	</video>
</div>
```
优点：全屏显示，无控制条
缺点：导航栏消失，某些机型退出播放时会有短暂黑屏。

第二种
```js
<div ontouchmove="{return false}" onclick="{return false}">
	<video id="video" playsinline="true">
	</video>
</div>
```
然后设置视频video标签样式：
```css
        video {
          margin: 0;
          padding: 0;
          width: 100%;
          //height: 100%;   ios设置该属性可以达到全屏显示，但稍有压缩，android会屏幕两边留有黑边。
          object-fit: fill;
          object-position: top;
          z-index: 2;
          position: relative;
          user-select: none;
          outline: none;
        }
```
优点：有导航栏，退出播放无黑屏
缺点：其实是有控制条的，但是通过禁止用户触摸和点击，把控制条隐藏在界面外，导致界面缺失。
		  如果设置高度，可能导致android机型屏幕两边留有黑边，与视屏的尺寸有一定关系。而且不同的机型的表    现不同。
		  
## 自动播放
这个就不用说了，安卓始终不支持自动播放。ios本来也不行，必须引导用户点击，但微信提供了一个事件WeixinJSBridgeReady，在微信嵌入webview全局的这个事件触发后，视频仍可以自动播放。
```js
document.addEventListener("WeixinJSBridgeReady", function (){ 
		video.play();
}, false)
```

## 关于播放控制
尽量只用timeupdate与ended两个事件，其他的诸如'loadstart','canplay','canplaythrough','ended','timeupdate'.....等等，会产生不一致的效果，不建议使用。

## 支持的格式
当前，video 元素支持三种视频格式：

Ogg = 带有 Theora 视频编码和 Vorbis 音频编码的 Ogg 文件

MPEG4 = 带有 H.264 视频编码和 AAC 音频编码的 MPEG 4 文件

WebM = 带有 VP8 视频编码和 Vorbis 音频编码的 WebM 文件

当然了，最好使用mp4的，移动端支持较好。
如果你想保险起见，可以写成这样：
```js
<video autoplay>
    <source src="video.mp4" type="video/mp4">
    <source src="video.webm" type="video/webm">
    <source src="video.ogv" type="video/ogg">
</video>
```
done.

下面附上文章最开始案例的code：
需求：全屏展示，保留title，不显示控制条，可嵌入APP
vue如下：
```js
      <div class="page-two" v-el:pagetwo v-if="showTwo" ontouchmove="{return false}" onclick="{return false}">
        <div class="video-wrap">
          <video id="video" src="//img.dsimg.cn/m_station/special_events/new_year_friend_circle/video1.mp4"
                 poster="//img.dsimg.cn/m_station/special_events/new_year_friend_circle/begin.jpg"
                 preload="auto"
                 x-webkit-airplay="allow"
                 webkit-playsinline="true"
                 playsinline="true"
                 @timeupdate="update()"
                 @ended="playEnd()"
                 v-el:video
                 class="translate">
            您的设备或浏览器暂不支持 video 标签。
          </video>
          <!--<div class="ignore ignore2" @click="playEnd()" v-if="showIgnore && isiOS && !isQQ">跳过</div>-->
          <div class="ignore" @click="playEnd()" v-if="showIgnore && isiOS && !isQQ"><img src="//img.dsimg.cn/m_station/special_events/new_year_friend_circle/jump.png"></div>
        </div>
      </div>
```
样式如下：
```css
    .page-two {
      position: absolute;
      z-index: 3;
      top: 0;
      left: 0;
      width: 100%;
      height: 100%;
      background-color: black;
      .video-wrap {
        position: relative;
        width: 100%;
        height: 100%;
        video {
          margin: 0;
          padding: 0;
          //height: 100%;  // 暂时保留，ios设置该属性可以达到全屏显示，但稍有压缩，android会屏幕两边留有黑边。
          object-fit: fill;
          object-position: top;
          z-index: 2;
          position: relative;
          user-select: none;
          outline: none;
        }
      }
    }
```
