### ISSUE TITLE
解决input光标不居中问题

### ISSUE THREAD

**Issue by KangXueLiang** [KangXueLiang/my-blog#4]
大家应该都知道，在Input里让文字垂直居中有很多种方案，最直接了当的一种：
```css
input {
  height: 20px;
  line-height: 20px;
}
```
但移动端很明显的有一种bug就是，未输入文字时Input里的光标与input一样高，输入文字后，光标行为也变得很怪异，见图：
<img src="http://oxpghhb5d.bkt.clouddn.com/imput-one.png" alt="[input光标样式bug" width = "300px"></img>
<img src="http://oxpghhb5d.bkt.clouddn.com/input-two.png" alt="[input光标样式bug" width = "300px"></img>
原因分析：
首先
IE：不管该行有没有文字，光标高度与font-size一致。

FF：该行有文字时，光标高度与font-size一致。该行无文字时，光标高度与input的height一致。

Chrome：该行无文字时，光标高度与line-height一致；该行有文字时，光标高度从input顶部到文字底部(这两种情况都是在有设定line-height的时候)，如果没有line-height，则是与font-size一致。

解决方法：
1、给input设置一个较小的height，然后上下用padding填充起来
```css
input{
    height: 16px;
    padding: 4px 0px;
    font-size: 12px;
}
```
2、 外面包一层，然后给input设置一个较小的line-height
```css
div {
  height: 20px;
  line-height: 20px;
}
div input {
  height: 20px;
  line-height: 10px
}
```
这样，光标就跟input的line-height一样了，看起来也和谐很多。
效果如下：
<img src="http://oxpghhb5d.bkt.clouddn.com/input-three.png" alt="[input光标样式bug" width = "300px"></img>
<img src="http://oxpghhb5d.bkt.clouddn.com/input-four.png" alt="[input光标样式bug" width = "300px"></img>
