### ISSUE TITLE
文本溢出显示省略号的具体实现

### ISSUE THREAD

**Issue by KangXueLiang** [KangXueLiang/my-blog#6]
项目中，经常会遇到实现文本溢出呈省略号，有的要求单行文本 ，有的要求多行文本，具体代码如下：

1、单行文本
``` css
div {
  width: 100px;
  overflow: hidden;
  text-overflow:ellipsis;
  white-space: nowrap;
}
```

2、多行文本
``` css
div {
  width: 100px;
  display: -webkit-box;
  -webkit-box-orient: vertical;
  -webkit-line-clamp: 3;
  overflow: hidden;
}
```
(因使用了WebKit的CSS扩展属性，该方法适用于WebKit浏览器及移动端)

注：
-webkit-line-clamp用来限制在一个块元素显示的文本的行数。 为了实现该效果，它需要组合其他的WebKit属性。常见结合属性：
display: -webkit-box; 必须结合的属性 ，将对象作为弹性伸缩盒子模型显示 。
-webkit-box-orient 必须结合的属性 ，设置或检索伸缩盒对象的子元素的排列方式 。
